"""Criacao da tabela tasks_categories

Revision ID: 5927792f3762
Revises: aba7b778058c
Create Date: 2021-06-20 18:07:01.692350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5927792f3762'
down_revision = 'aba7b778058c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_categories')
    # ### end Alembic commands ###
